import { describe, it, expect } from 'vitest';
import type { WorkspaceContent } from '@/lib/schema/types';
import { generateTableSQL, generateScript, escapeId, escapeStr } from './generate';

const content: WorkspaceContent = {
  schemaVersion: 1,
  settings: { defaultEngine: 'InnoDB', defaultCharset: 'utf8mb4', defaultCollation: 'utf8mb4_0900_ai_ci' },
  viewport: { x: 0, y: 0, zoom: 1 },
  logicalEdges: [{ id: 'l1', fromTableId: 't1', fromColumnId: 'c2', toTableId: 't2', cardinality: 'm-1', label: 'soft' }],
  tables: [
    {
      id: 't1', name: 'orders', x: 0, y: 0, w: 220, comment: "order's table", autoIncrementStart: 1000,
      columns: [
        { id: 'c1', name: 'id', type: { base: 'bigint' }, nullable: false, unsigned: true, autoIncrement: true },
        { id: 'c2', name: 'user_id', type: { base: 'int' }, nullable: false, unsigned: true },
        { id: 'c3', name: 'status', type: { base: 'enum', values: ['new', 'paid'] }, nullable: false, default: { kind: 'literal', value: 'new' } },
        { id: 'c4', name: 'meta', type: { base: 'json' }, nullable: true, default: { kind: 'expression', value: 'json_object()' } },
        { id: 'c5', name: 'placed_at', type: { base: 'datetime', fsp: 3 }, nullable: false,
          default: { kind: 'current_timestamp', fsp: 3 }, onUpdateCurrentTimestamp: true, onUpdateFsp: 3 },
        { id: 'c6', name: 'note', type: { base: 'varchar', length: 255 }, nullable: true,
          charset: 'utf8mb4', collation: 'utf8mb4_bin', comment: 'free text', default: { kind: 'null' } },
        { id: 'c7', name: 'loc', type: { base: 'point', srid: 4326 }, nullable: false },
        { id: 'c8', name: 'cents', type: { base: 'bigint' }, nullable: true, generated: { expression: '`id` * 100', stored: true } },
      ],
      indexes: [
        { id: 'i1', name: 'PRIMARY', kind: 'primary', visible: true, columns: [{ columnId: 'c1' }] },
        { id: 'i2', name: 'uq_orders_user', kind: 'unique', visible: true, columns: [{ columnId: 'c2' }, { columnId: 'c3' }] },
        { id: 'i3', name: 'idx_note', kind: 'index', visible: false, columns: [{ columnId: 'c6', length: 20, order: 'DESC' }] },
        { id: 'i4', name: 'sp_loc', kind: 'spatial', visible: true, columns: [{ columnId: 'c7' }] },
        { id: 'i5', name: 'empty', kind: 'index', visible: true, columns: [] },
      ],
      foreignKeys: [
        { id: 'f1', name: 'fk_orders_users', columnIds: ['c2'], refTableId: 't2', refColumnIds: ['u1'], onDelete: 'CASCADE', onUpdate: 'RESTRICT' },
      ],
    },
    {
      id: 't2', name: 'users', x: 0, y: 0, w: 220,
      columns: [{ id: 'u1', name: 'id', type: { base: 'int' }, nullable: false, unsigned: true, autoIncrement: true }],
      indexes: [{ id: 'iu', name: 'PRIMARY', kind: 'primary', visible: true, columns: [{ columnId: 'u1' }] }],
      foreignKeys: [],
    },
  ],
};

describe('escapes', () => {
  it('escapes identifiers and strings', () => {
    expect(escapeId('we`ird')).toBe('`we``ird`');
    expect(escapeStr("it's a \\ test")).toBe("it''s a \\\\ test");
  });
});

describe('generateTableSQL', () => {
  it('emits the exact CREATE TABLE', () => {
    expect(generateTableSQL(content.tables[0], content)).toBe(
`CREATE TABLE \`orders\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`user_id\` int unsigned NOT NULL,
  \`status\` enum('new','paid') NOT NULL DEFAULT 'new',
  \`meta\` json NULL DEFAULT (json_object()),
  \`placed_at\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  \`note\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT 'free text',
  \`loc\` point NOT NULL SRID 4326,
  \`cents\` bigint GENERATED ALWAYS AS (\`id\` * 100) STORED NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uq_orders_user\` (\`user_id\`, \`status\`),
  KEY \`idx_note\` (\`note\`(20) DESC) INVISIBLE,
  SPATIAL KEY \`sp_loc\` (\`loc\`),
  CONSTRAINT \`fk_orders_users\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='order''s table';`);
  });
});

describe('generateScript', () => {
  it('wraps with FK checks and appends logical comments', () => {
    const s = generateScript(content);
    expect(s.startsWith('-- Generated by ER Workspace — MySQL 8.0\nSET FOREIGN_KEY_CHECKS=0;')).toBe(true);
    expect(s).toContain('SET FOREIGN_KEY_CHECKS=1;');
    expect(s).toContain('-- logical: {"from":"orders.user_id","to":"users","cardinality":"m-1","label":"soft"}');
    expect(s.indexOf('CREATE TABLE `orders`')).toBeLessThan(s.indexOf('CREATE TABLE `users`'));
  });
});
