import type { Column, ForeignKey, Table, TableIndex, WorkspaceContent } from '../schema/types';
import { formatType, isSpatialType } from '../schema/datatypes';

export const escapeId = (s: string) => '`' + s.replace(/`/g, '``') + '`';
export const escapeStr = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "''");

const colName = (t: Table, id: string) => t.columns.find(c => c.id === id)?.name ?? '?';

export function generateColumnSQL(col: Column): string {
  const parts: string[] = [escapeId(col.name), formatType(col.type)];
  if (col.unsigned) parts.push('unsigned');
  if (col.zerofill) parts.push('zerofill');
  if (col.charset) parts.push(`CHARACTER SET ${col.charset}`);
  if (col.collation) parts.push(`COLLATE ${col.collation}`);
  if (col.generated)
    parts.push(`GENERATED ALWAYS AS (${col.generated.expression}) ${col.generated.stored ? 'STORED' : 'VIRTUAL'}`);
  parts.push(col.nullable ? 'NULL' : 'NOT NULL');
  if (col.type.srid != null && isSpatialType(col.type.base)) parts.push(`SRID ${col.type.srid}`);
  if (col.default && !col.generated) {
    if (col.default.kind === 'null') parts.push('DEFAULT NULL');
    else if (col.default.kind === 'literal') parts.push(`DEFAULT '${escapeStr(col.default.value ?? '')}'`);
    else if (col.default.kind === 'expression') parts.push(`DEFAULT (${col.default.value ?? 'NULL'})`);
    else parts.push(`DEFAULT CURRENT_TIMESTAMP${col.default.fsp ? `(${col.default.fsp})` : ''}`);
  }
  if (col.onUpdateCurrentTimestamp)
    parts.push(`ON UPDATE CURRENT_TIMESTAMP${col.onUpdateFsp ? `(${col.onUpdateFsp})` : ''}`);
  if (col.autoIncrement && !col.generated) parts.push('AUTO_INCREMENT');
  if (col.comment) parts.push(`COMMENT '${escapeStr(col.comment)}'`);
  return parts.join(' ');
}

export function generateIndexSQL(ix: TableIndex, t: Table): string {
  const cols = ix.columns.map(ic => {
    let s = escapeId(colName(t, ic.columnId));
    if (ic.length != null) s += `(${ic.length})`;
    if (ic.order === 'DESC') s += ' DESC';
    return s;
  }).join(', ');
  const inv = ix.visible === false ? ' INVISIBLE' : '';
  switch (ix.kind) {
    case 'primary': return `PRIMARY KEY (${cols})`;
    case 'unique': return `UNIQUE KEY ${escapeId(ix.name)} (${cols})${inv}`;
    case 'fulltext': return `FULLTEXT KEY ${escapeId(ix.name)} (${cols})`;
    case 'spatial': return `SPATIAL KEY ${escapeId(ix.name)} (${cols})`;
    default: return `KEY ${escapeId(ix.name)} (${cols})${inv}`;
  }
}

export function generateFkSQL(fk: ForeignKey, t: Table, c: WorkspaceContent): string {
  const ref = c.tables.find(x => x.id === fk.refTableId);
  const local = fk.columnIds.map(id => escapeId(colName(t, id))).join(', ');
  const remote = fk.refColumnIds.map(id => (ref ? escapeId(colName(ref, id)) : '`?`')).join(', ');
  let s = `CONSTRAINT ${escapeId(fk.name)} FOREIGN KEY (${local}) REFERENCES ${escapeId(ref?.name ?? '?')} (${remote})`;
  if (fk.onDelete) s += ` ON DELETE ${fk.onDelete}`;
  if (fk.onUpdate) s += ` ON UPDATE ${fk.onUpdate}`;
  return s;
}

export function generateTableSQL(t: Table, c: WorkspaceContent): string {
  const lines = [
    ...t.columns.map(col => '  ' + generateColumnSQL(col)),
    ...t.indexes.filter(ix => ix.columns.length > 0).map(ix => '  ' + generateIndexSQL(ix, t)),
    ...t.foreignKeys.map(fk => '  ' + generateFkSQL(fk, t, c)),
  ];
  const opts = [`ENGINE=${t.engine ?? c.settings.defaultEngine}`];
  if (t.autoIncrementStart != null) opts.push(`AUTO_INCREMENT=${t.autoIncrementStart}`);
  opts.push(`DEFAULT CHARSET=${t.charset ?? c.settings.defaultCharset}`);
  // a table-level charset override without an explicit collation must NOT inherit the
  // workspace-default collation (it may belong to a different charset) — let MySQL pick
  const collation = t.collation ?? (t.charset ? undefined : c.settings.defaultCollation);
  if (collation) opts.push(`COLLATE=${collation}`);
  if (t.comment) opts.push(`COMMENT='${escapeStr(t.comment)}'`);
  return `CREATE TABLE ${escapeId(t.name)} (\n${lines.join(',\n')}\n) ${opts.join(' ')};`;
}

export function generateScript(c: WorkspaceContent): string {
  const logical = c.logicalEdges.flatMap(e => {
    const from = c.tables.find(t => t.id === e.fromTableId);
    const to = c.tables.find(t => t.id === e.toTableId);
    if (!from || !to) return [];
    const fc = e.fromColumnId ? from.columns.find(x => x.id === e.fromColumnId)?.name : undefined;
    const tc = e.toColumnId ? to.columns.find(x => x.id === e.toColumnId)?.name : undefined;
    const payload: Record<string, string> = {
      from: fc ? `${from.name}.${fc}` : from.name,
      to: tc ? `${to.name}.${tc}` : to.name,
      cardinality: e.cardinality,
    };
    if (e.label) payload.label = e.label;
    return [`-- logical: ${JSON.stringify(payload)}`];
  });
  return [
    '-- Generated by ER Workspace — MySQL 8.0',
    'SET FOREIGN_KEY_CHECKS=0;',
    '',
    ...c.tables.map(t => generateTableSQL(t, c) + '\n'),
    'SET FOREIGN_KEY_CHECKS=1;',
    ...(logical.length ? ['', ...logical] : []),
    '',
  ].join('\n');
}
